### ISSUE TITLE
instant.io

### ISSUE THREAD

**Issue by desci** [piratas/gti#59]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

<https://torrent.partidopirata.org>

---

Código fonte: <https://github.com/piratas/instant.io>

## TODO

- [ ] Alterar o logotipo para algum temático do partido

- [ ] Usar um servidor TURN

- [ ] Listar como espelho no site principal

- [ ] Docker

- [ ] Fazer link para o site do partido

- [ ] Traduzir alguma palestra do @feross pra português ou inventar um resumo novo sobre web torrent e instant.io
