### ISSUE TITLE
Wordpress pra Goiás

### ISSUE THREAD

**Issue by desci** [piratas/gti#60]
*Se a pergunta não se aplicar, deixe sem resposta*

### A que site, ferramenta ou coisa esta questão está relacionada?

<https://goias.partidopirata.org>

---

### Descreva a ideia, projeto, sugestão, use quantas palavras quiser ou precisar:

Enviado por telegram:

> Queria ver se haveria possibilidade de ter um espaço em um servidor para um blog de Goiás.

### Quem vai ser responsável por organizar?

    não sei

---

## TODO

- [ ] Dockerfile

- [ ] Repositório git

- [ ] Instalar no servidor *(e criar um [script](https://github.com/piratas/scripts.d) pra isto)*

- [ ] Acrescentar subdomínio no certificado SSL *(e criar um [script](https://github.com/piratas/scripts.d) pra isto)*

- [ ] Enviar as credenciais de administração pra Givaldo Corcinio
